### ISSUE TITLE
File.allowed_extensions does not support files with . in filename but allows upload

### ISSUE THREAD

**Issue by brettt89** [silverstripe/silverstripe-assets#266]
As per Issue #141 . Filenames with dots in them are no longer supported in SS4. However no validation appears to be done during upload / (file/folder) creation (in CMS) that the filename / foldername does not contain any dots in them.

This means users are getting succesful "upload" messages from CMS, but are not able to see the preview or file content due to `.htaccess` blocking these files.

We should also validate file uploads / folder creations to ensure that they do not contain dots within the filename or foldername.

**Comment by michalkleiner** [comment]
I'd rather review the hard limitation of not allowing dots in filenames which is not a super-rare thing.

**Comment by BlinkTwice** [comment]
I agree with @michalkleiner , dots within file names are quite common but I don't know the code base well enough to know how large the implications are. If it helps anyone, however, my quick fix for this was to override the [template](https://github.com/silverstripe/silverstripe-assets/blob/0f50a3ea413399cf47875d26f3a634c5b4617a5e/templates/SilverStripe/Assets/Flysystem/PublicAssetAdapter_HTAccess.ss#L28) with...
`RewriteCond %{REQUEST_URI} !^.*\.(?i:css|js<% loop $AllowedExtensions %>|$Extension<% end_loop %>)$`

**Comment by chillu** [comment]
The issue you referenced talked about a limitation of dots in *folder names*. I'd say that's much more rare than in *file names*. Looking at my 4.4 install, I can both upload files with dots in the filename, and download them as protected files (through PHP) and public files (through Apache).

Looking at `public/assets/.htaccess`, the regex just checks that there's a valid extension *at the end* of the file - see regexr.com/4g6c0. If you have this issue with files, can you provide a sample filename and steps on how you check upload/download, plus your infrastructure setup (e.g. just Apache, nginx, etc)

**Comment by BlinkTwice** [comment]
Yep - my bad. I was on the wrong version. I can see this was corrected way back: https://github.com/silverstripe/silverstripe-assets/commit/0c713b5b1eb6a08ac00dcadb187b8b3ef7115fc4

**Comment by chillu** [comment]
OK, then this is a duplicate of https://github.com/silverstripe/silverstripe-asset-admin/issues/830

**Comment by elliot-sawyer** [comment]
I'm still getting this issue in 4.8, when generating a file containing "V4.3-month-year.pdf".  I get an error: "the extension 3-month-year.pdf is not allowed"
